# Generated by Django 3.0.1 on 2020-01-12 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('RD', 'Красная'), ('BL', 'Синяя'), ('WM', 'Арбузик')], max_length=2, verbose_name='Название сцены')),
                ('description', models.CharField(max_length=300, verbose_name='Описание сцены')),
                ('first_day_afternoon', models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день днём')),
                ('first_day_evn', models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день вечером')),
                ('first_day_late_evn', models.PositiveIntegerField(default=0, verbose_name='Количество групп в 1-ый день поздним вечером')),
                ('second_day_afternoon', models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день днём')),
                ('second_day_evn', models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день вечером')),
                ('second_day_late_evn', models.PositiveIntegerField(default=0, verbose_name='Количество групп в 2-ой день поздним вечером')),
            ],
            options={
                'verbose_name': 'Сцена',
                'verbose_name_plural': 'Сцены',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, max_length=30, unique=True)),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('format', models.CharField(choices=[('GR', 'Группа'), ('SO', 'Сольное выступление')], max_length=2, verbose_name='Формат выступления')),
                ('name', models.CharField(max_length=30, verbose_name='Имя группы или исполнителя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.IntegerField(default=0, verbose_name='Рейтинг')),
                ('accepted', models.BooleanField(default=False, verbose_name='Одобрено')),
                ('denied', models.BooleanField(default=False, verbose_name='Отказано')),
                ('scene', models.CharField(choices=[('RD', 'Красная'), ('BL', 'Синяя'), ('WM', 'Арбузик')], max_length=2, verbose_name='Желаемая сцена')),
                ('performance_day', models.CharField(choices=[('FR', 'Пятница'), ('SA', 'Суббота')], max_length=2, verbose_name='Желаемый день выступления')),
                ('wishes', models.CharField(blank=True, max_length=250, verbose_name='Пожелания')),
                ('abstain', models.ManyToManyField(blank=True, related_name='abstain', to='user_profiles.UserProfile', verbose_name='Воздерживаюсь')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to='user_profiles.UserProfile', verbose_name='Не нравится')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to='user_profiles.UserProfile', verbose_name='Нравится')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_profiles.UserProfile')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
