# Generated by Django 2.2.9 on 2020-01-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festival_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Имя группы или исполнителя'),
        ),
    ]
